### ISSUE TITLE
FEATURE: schema from data

### ISSUE THREAD

**Issue by kshpytsya** [crdoconnor/strictyaml#16] opened 2017-02-03 20:37 UTC
Provide a way to construct schema from data. This would make it possible to have schema stored as a yaml file. I have a specific use case for this in the project that I am currently developing. Roughly speaking, there are several tiers of configurability, the first being the data and the second, among the other things, is the schema for that data. Currently I am using [Cerberus](http://docs.python-cerberus.org/en/stable/) for that purpose but since I intend to use `strictyaml` anyway, it feels a bit awkward to have two validators in the codebase.
Of course, I could build this functionality atop of `strictyaml` myself, but then I would need to both keep it in sync with `stricyaml` (should any new validators be added in the future) and write the end user documentation on "schema schema" whereas with `Cerberus` I can rely on existing documentation and just refer end-user to it.

**Comment by crdoconnor** [comment] 2017-02-03 21:08
I'm not sure about this one. You can already read unstructured, schemaless data using strictyaml and you can also create partial schemas. You can ratchet up the strictness incrementally rather than generating a great big schema (which will likely change).

I'm also pretty averse to writing code generation tools (I've seen them go wrong too many times).

I'm intending on allowing the use of kwalify schemas at some point, but since these don't work for more complex schemas, it would be alongside the existing pythonic schema language.

**Comment by kshpytsya** [comment] 2017-02-03 22:24
Correct me if I am mistaken, but I see at as very straightforward recursive constructor for validators with uniform direct correspondence to existing python validator classes and their parameters.
This would be trivial to implement but would be a pain to keep up-to-date if not being part of the `strictyaml` itself. I suspect that creative (isn't it always?) use of decorators on Validator classes could make this simple and elegant.

I don't quite get your remark on "code generation tools".

**Comment by crdoconnor** [comment] 2017-02-04 17:55
Are you suggesting something like this::

    x:
      a: 1
      b: 2

    strictyaml.generate_schema(yaml_string) == """Map({"a": Int(), "b": Int()})"""

**Comment by kshpytsya** [comment] 2017-02-04 19:32
No. Rather:

```
Map({
    "u": Seq(Bool),
    "x": Int(),
    "y": Enum(["a", "b", "c"]),
    "z": MapPattern(Int(), Str())
})
```

should be described as:

```
type: Map
validator:
    - u:
        type: Seq
        validator:
            type: Bool
    - x:
        type: Int
    - y:
        type: Enum
        restricted_to:
              - a
              - b
              - c
    - z:
        type: MapPattern
        key_validator:
            type: Int
        value_validator:
            type: Str
```

The values in "type" can be any of the leaf Validator classes (I am not sure if all classes in the `validators` module are meant to be usable by the user, or rather some are meant as base classes only). The rest of the keys should correspond to constructor arguments. 
Just as I said earlier, I believe that something like that can be elegantly implementing by some decorators decorating `Validator` subclasses.

**Comment by crdoconnor** [comment] 2017-02-15 20:23
Yes, I'd like to do this feature like so::

    data = strictyaml.load(yaml_str, Kwalify(kwalify_schema_str))

>Defining schema in Python is, of course, more concise, but in my use case, I need the ability to give the end-user a way to describe schema without resorting to Python programming, following the rule of least power.

Sure, I think YAML is sometimes better provided it can represent the schema you need.

**Comment by crdoconnor** [comment] 2017-02-15 20:24
I'm not sure if constructing the schema from data belongs in this library though. That might work better as a separate library.

**Comment by crdoconnor** [comment] 2017-11-26 18:05
On second thoughts, I think I'm going to close this. I think it's a decent enough idea in principle, but:

* In all the time I've been dogfooding this library, I haven't really felt the desire to use kwalify (or something similar) instead. By contrast this library exists because I was frustrated by kwalify's limitations. I'm not 100% convinced, but I'm edging around to the view that turning off turing completeness in schemas is a mistake.

*  I think if it did exist it would work better as a separate library that generates a strictyaml validator from a kwalify YAML string.

If somebody else builds this as a separate library I'll be happy to point people to it in the README and docs in the relevant place, run tests on it as part of the regression test suite and provide any help as necessary though.

**Closed by crdoconnor** 2017-11-26 18:05 UTC
